insert into Actor values
(1,"제니퍼 로렌스","Jennifer Lawrence","미국","https://www.facebook.com/JenniferLawrence/","미국사람이다"),
(2,"조시 허처슨","Josh Hutcherson","미국","https://twitter.com/jhutch1992","남자사람이다"),
(3,"한효주","Hyo Joo Han","대한민국","https://www.instagram.com/hanhyojoo222/","한효주다"),
(4, "박서준", "Seo Jun Park", "대한민국", "https://instagram.com/bn_sj2013", "박서준이다"),
(5, "벤 버트", "Ben Burtt", "미국", "https://www.skysound.com/people/ben-burtt/", "벤 버트이다"),
(6, "엘리사 나이트", "Elissa Knight", "미국", "https://www.imdb.com/name/nm2264184/", "엘리사 나이트이다"),
(7, "이선", "Sun Lee", "대한민국", "https://lordofvoice.com/leesun", "이선이다"),
(8, "이미자", "Mi Ja Lee", "대한민국", "google.com", "사이트가 없다."),
(9, "이디나 멘젤", "Idina Mentzel", "미국", "https://twitter.com/idinamenzel", "이디나 멘젤이다"),
(10,"크리스틴 벨","Kristen Bell","미국","https://twitter.com/IMKristenBell","크리스틴 벨이다"),
(11,"조진웅","Jin Woong Cho","대한민국","http://esaram.co.kr/ko/chojinwoong","조진웅이다"),
(12,"이하늬","Ha Nee Lee","대한민국","http://esaram.co.kr/ko/leehanee","이하늬이다"),
(13,"송강호","Kang Ho Song","대한민국","google.com","송강호이다"),
(14,"변희봉","Hee Bong Byun","대한민국","google.com","변희봉이다");
