insert into Actor values
(1000,"제니퍼 로렌스","Jennifer Lawrence","미국","https://www.facebook.com/JenniferLawrence/","미국사람이다"),
(1001,"조시 허처슨","Josh Hutcherson","미국","https://twitter.com/jhutch1992","남자사람이다"),
(1002,"한효주","Hyo Joo Han","대한민국","https://www.instagram.com/hanhyojoo222/","한효주다"),
(1003, "박서준", "Seo Jun Park", "대한민국", "https://instagram.com/bn_sj2013", "박서준이다"),
(1004, "벤 버트", "Ben Burtt", "미국", "https://www.skysound.com/people/ben-burtt/", "벤 버트이다"),
(1005, "엘리사 나이트", "Elissa Knight", "미국", "https://www.imdb.com/name/nm2264184/", "엘리사 나이트이다"),
(1006, "이선", "Sun Lee", "대한민국", "https://lordofvoice.com/leesun", "이선이다"),
(1007, "이미자", "Mi Ja Lee", "대한민국", "google.com", "사이트가 없다."),
(1008, "이디나 멘젤", "Idina Mentzel", "미국", "https://twitter.com/idinamenzel", "이디나 멘젤이다"),
(1009,"크리스틴 벨","Kristen Bell","미국","https://twitter.com/IMKristenBell","크리스틴 벨이다"),
(1010,"조진웅","Jin Woong Cho","대한민국","http://esaram.co.kr/ko/chojinwoong","조진웅이다"),
(1011,"이하늬","Ha Nee Lee","대한민국","http://esaram.co.kr/ko/leehanee","이하늬이다"),
(1012,"송강호","Kang Ho Song","대한민국","google.com","송강호이다"),
(1013,"변희봉","Hee Bong Byun","대한민국","google.com","변희봉이다"),
(1014,"서현진","Seo Hyunjin","대한민국","naver.com","서현진이다"),
(1015,"이민기","Moon Ji-in","대한민국","naver.com","문지인이다"),
(1016,"코자쿠라 에츠코","Kozakura etsuko","일본","naver.com","일본인이다"),
(1017,"토마츠 하루카","Tomatsu haruka","일본","naver.com","일본인이다");
